### ISSUE TITLE
Social Media

### ISSUE THREAD

**Issue by gwake1** [code-for-nashville/nashville_transparency_project#4]
Hi Dave and Stephania,

Consult with John and Jon regarding the creation of separate social media accounts for the NTP brand.

Consult on potentially creating facebook, twitter, and github accounts.

Also try to get additional info on the NTP being featured more prominently in Code for Nashville meetups.

**Comment by OAuthBringer** [comment]
I'd say this is currently beyond the current scope of the project.  We will probably utilize existing Code for Nashville outlets to promote NTP.
